source 'http://rubygems.org'

gem 'uglifier', '>= 2.7.2'
gem 'jekyll'
gem 'jekyll-sitemap'
gem 'jekyll-assets'
gem 'github-markdown'
gem 'html-pipeline'
gem 'activesupport', '~> 4.1.11'
gem 'nokogiri', '>= 1.6.8'
gem 'redcarpet', '>= 3.2.3'
